In [2]:
import pandas as pd

df = pd.read_csv('synthetic_fraud_dataset.csv')

In [3]:
df.head()

,transaction_id,user_id,amount,transaction_type,merchant_category,country,hour,device_risk_score,ip_risk_score,is_fraud
0,9608,363,4922.587542,ATM,Travel,TR,12,0.992347,0.947908,1
1,456,692,48.018303,QR,Food,US,21,0.168571,0.224057,0
2,4747,587,136.881960,Online,Travel,TR,14,0.296127,0.125058,0
3,6934,445,80.534719,POS,Clothing,TR,23,0.124801,0.159243,0
4,1646,729,120.041158,Online,Grocery,FR,16,0.098129,0.027542,0

In [13]:
df[df['is_fraud'] == 1]

,transaction_id,user_id,amount,transaction_type,merchant_category,country,hour,device_risk_score,ip_risk_score,is_fraud
0,9608,363,4922.587542,ATM,Travel,TR,12,0.992347,0.947908,1
23,9933,121,4284.177967,ATM,Food,TR,12,0.737854,0.731071,1
84,9637,560,1148.378114,POS,Travel,DE,19,0.945709,0.835616,1
87,9711,935,952.547905,QR,Travel,UK,20,0.783611,0.985521,1
89,9939,291,2865.421641,ATM,Food,TR,13,0.834843,0.904304,1
...,...,...,...,...,...,...,...,...,...,...
9787,9762,217,1455.533469,QR,Food,TR,4,0.893687,0.957413,1
9794,9634,185,2231.990705,QR,Clothing,UK,7,0.750121,0.727340,1
9814,9695,607,18.620488,QR,Travel,FR,12,0.773951,0.741442,1
9856,9947,123,1381.201430,POS,Food,US,19,0.940389,0.818065,1
9991,9644,953,1546.529140,POS,Clothing,FR,4,0.845571,0.926432,1

In [15]:
df[df['is_fraud'] == 0]

,transaction_id,user_id,amount,transaction_type,merchant_category,country,hour,device_risk_score,ip_risk_score,is_fraud
1,456,692,48.018303,QR,Food,US,21,0.168571,0.224057,0
2,4747,587,136.881960,Online,Travel,TR,14,0.296127,0.125058,0
3,6934,445,80.534719,POS,Clothing,TR,23,0.124801,0.159243,0
4,1646,729,120.041158,Online,Grocery,FR,16,0.098129,0.027542,0
5,2183,944,97.108625,POS,Clothing,DE,17,0.235399,0.105454,0
...,...,...,...,...,...,...,...,...,...,...
9995,1076,482,58.366442,POS,Clothing,DE,12,0.066366,0.086344,0
9996,4995,904,139.502160,POS,Travel,DE,13,0.119014,0.285680,0
9997,3485,527,71.012122,Online,Travel,TR,8,0.119204,0.262262,0
9998,7922,771,21.031405,QR,Grocery,UK,12,0.027088,0.295243,0
9999,6451,429,54.028632,ATM,Electronics,DE,11,0.096438,0.042823,0

In [22]:
df['is_fraud'].value_counts()

is_fraud
0    9500
1     500
Name: count, dtype: int64

In [21]:
(df['is_fraud'] == 1).mean() * 100

np.float64(5.0)

In [20]:
(df['is_fraud'] == 0).mean() * 100

np.float64(95.0)

In [24]:
df.loc[len(df)] = [10001,9999,123.23,'ATM','Travel','US',20,0.2,0.9,1]

In [25]:
df.tail()

,transaction_id,user_id,amount,transaction_type,merchant_category,country,hour,device_risk_score,ip_risk_score,is_fraud
9996,4995,904,139.502160,POS,Travel,DE,13,0.119014,0.285680,0
9997,3485,527,71.012122,Online,Travel,TR,8,0.119204,0.262262,0
9998,7922,771,21.031405,QR,Grocery,UK,12,0.027088,0.295243,0
9999,6451,429,54.028632,ATM,Electronics,DE,11,0.096438,0.042823,0
10000,10001,9999,123.230000,ATM,Travel,US,20,0.200000,0.900000,1

In [26]:
df = df[df['hour'] >= 10]

In [27]:
df[df['hour'] < 10]

Empty DataFrame
Columns: [transaction_id, user_id, amount, transaction_type, merchant_category, country, hour, device_risk_score, ip_risk_score, is_fraud]
Index: []

In [28]:
df.isnull().sum()

transaction_id       0
user_id              0
amount               0
transaction_type     0
merchant_category    0
country              0
hour                 0
device_risk_score    0
ip_risk_score        0
is_fraud             0
dtype: int64

In [32]:
df = df.sort_values(by='transaction_id')

In [34]:
df

,transaction_id,user_id,amount,transaction_type,merchant_category,country,hour,device_risk_score,ip_risk_score,is_fraud
8110,0,21,60.949553,ATM,Travel,US,17,0.154740,0.277348,0
5227,1,348,112.994162,ATM,Travel,FR,23,0.163606,0.199545,0
2855,3,682,112.997900,Online,Food,TR,12,0.074832,0.199785,0
7674,6,905,177.909182,ATM,Travel,DE,16,0.107858,0.156698,0
4049,8,319,92.918951,Online,Electronics,US,20,0.216073,0.003987,0
...,...,...,...,...,...,...,...,...,...,...
8719,9993,328,1637.680200,QR,Grocery,US,13,0.938322,0.991046,1
9624,9995,478,2661.977484,QR,Clothing,UK,18,0.941775,0.983693,1
9667,9997,574,6427.530530,Online,Clothing,NG,15,0.760300,0.972874,1
9441,9998,411,3019.952898,POS,Food,US,23,0.834317,0.732515,1
10000,10001,9999,123.230000,ATM,Travel,US,20,0.200000,0.900000,1

In [35]:
df.to_csv('update.csv',index = False)