# Analisis Tren Pasar Maskapai Penerbangan AS (1993-2024)
**Oleh: Ardell Aghna Mahendra**

## 1. Import Library & Load Data

In [1]:
import pandas as pd
import numpy as np

df = pd.read_csv('US Airline Flight Routes and Fares 1993-2024.csv')

/var/folders/l2/xc7f33bj39j5wmk730d9bl300000gn/T/ipykernel_94305/4083832947.py:4: DtypeWarning: Columns (20,21) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('US Airline Flight Routes and Fares 1993-2024.csv')

### Melihat isi dataset

In [2]:
df.head()

,tbl,Year,quarter,citymarketid_1,citymarketid_2,city1,city2,airportid_1,airportid_2,airport_1,...,fare,carrier_lg,large_ms,fare_lg,carrier_low,lf_ms,fare_low,Geocoded_City1,Geocoded_City2,tbl1apk
0,Table1a,2021,3,30135,33195,"Allentown/Bethlehem/Easton, PA","Tampa, FL (Metropolitan Area)",10135,14112,ABE,...,81.43,G4,1.0000,81.43,G4,1.0000,81.43,NaN,NaN,202131013514112ABEPIE
1,Table1a,2021,3,30135,33195,"Allentown/Bethlehem/Easton, PA","Tampa, FL (Metropolitan Area)",10135,15304,ABE,...,208.93,DL,0.4659,219.98,UA,0.1193,154.11,NaN,NaN,202131013515304ABETPA
2,Table1a,2021,3,30140,30194,"Albuquerque, NM","Dallas/Fort Worth, TX",10140,11259,ABQ,...,184.56,WN,0.9968,184.44,WN,0.9968,184.44,NaN,NaN,202131014011259ABQDAL
3,Table1a,2021,3,30140,30194,"Albuquerque, NM","Dallas/Fort Worth, TX",10140,11298,ABQ,...,182.64,AA,0.9774,183.09,AA,0.9774,183.09,NaN,NaN,202131014011298ABQDFW
4,Table1a,2021,3,30140,30466,"Albuquerque, NM","Phoenix, AZ",10140,14107,ABQ,...,177.11,WN,0.6061,184.49,AA,0.3939,165.77,NaN,NaN,202131014014107ABQPHX

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 245955 entries, 0 to 245954
Data columns (total 23 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   tbl             245955 non-null  object
 1   Year            245955 non-null  int64
 2   quarter         245955 non-null  int64
 3   citymarketid_1  245955 non-null  int64
 4   citymarketid_2  245955 non-null  int64
 5   city1           245955 non-null  object
 6   city2           245955 non-null  object
 7   airportid_1     245955 non-null  int64
 8   airportid_2     245955 non-null  int64
 9   airport_1       245955 non-null  object
 10  airport_2       245955 non-null  object
 11  nsmiles         245955 non-null  int64
 12  passengers      245955 non-null  int64
 13  fare            245955 non-null  float64
 14  carrier_lg      244415 non-null  object
 15  large_ms        244415 non-null  float64
 16  fare_lg         244415 non-null  float64
 17  carrier_low     244343 non-null  object
 18  lf_ms           244343 non-null  float64
 19  fare_low        244343 non-null  float64
 20  Geocoded_City1  206749 non-null  object
 21  Geocoded_City2  206749 non-null  object
 22  tbl1apk         245955 non-null  object
dtypes: float64(5), int64(8), object(10)
memory usage: 43.2+ MB

In [4]:
df.describe()

,Year,quarter,citymarketid_1,citymarketid_2,airportid_1,airportid_2,nsmiles,passengers,fare,large_ms,fare_lg,lf_ms,fare_low
count,245955.000000,245955.000000,245955.000000,245955.000000,245955.000000,245955.000000,245955.000000,245955.000000,245955.000000,244415.000000,244415.000000,244343.000000,244343.000000
mean,2008.524124,2.479153,31556.430201,32180.117086,12437.099986,13249.889525,1189.812319,299.476795,218.979587,0.665252,218.710963,0.450438,190.675939
std,8.703364,1.122149,1089.872880,1232.464184,1431.665257,1425.810159,703.143472,511.389486,82.372486,0.224635,84.674363,0.332669,73.577694
min,1993.000000,1.000000,30135.000000,30189.000000,10135.000000,10466.000000,109.000000,0.000000,50.000000,0.003800,50.000000,0.010000,50.000000
25%,2001.000000,1.000000,30721.000000,30994.000000,11193.000000,12197.000000,626.000000,21.000000,164.620000,0.480000,161.500000,0.158000,140.060000
50%,2008.000000,2.000000,31423.000000,32211.000000,12266.000000,13303.000000,1023.000000,113.000000,209.320000,0.652400,208.030000,0.360000,181.630000
75%,2016.000000,3.000000,32467.000000,33192.000000,13487.000000,14679.000000,1736.000000,339.000000,262.890000,0.871900,263.640000,0.750000,230.040000
max,2024.000000,4.000000,35412.000000,35628.000000,16440.000000,15919.000000,2724.000000,8301.000000,3377.000000,1.000000,2725.600000,1.000000,2725.600000

In [5]:
df.isnull().sum()

tbl                   0
Year                  0
quarter               0
citymarketid_1        0
citymarketid_2        0
city1                 0
city2                 0
airportid_1           0
airportid_2           0
airport_1             0
airport_2             0
nsmiles               0
passengers            0
fare                  0
carrier_lg         1540
large_ms           1540
fare_lg            1540
carrier_low        1612
lf_ms              1612
fare_low           1612
Geocoded_City1    39206
Geocoded_City2    39206
tbl1apk               0
dtype: int64

## 2. Data Cleaning & Preparation
### Memilih kolom relevan dan membuat dataframe baru

In [6]:
# Memilih kolom utama yang relevan untuk analisis
selected_columns = ['Year', 'quarter', 'city1', 'city2', 'airport_1', 'airport_2', 'passengers', 'fare', 'carrier_lg', 'nsmiles']

# Membuat dataframe baru yang hanya berisikan kolom-kolom di atas
df_clean = df[selected_columns].copy()

# Cek hasilnya
df_clean.head()

,Year,quarter,city1,city2,airport_1,airport_2,passengers,fare,carrier_lg,nsmiles
0,2021,3,"Allentown/Bethlehem/Easton, PA","Tampa, FL (Metropolitan Area)",ABE,PIE,180,81.43,G4,970
1,2021,3,"Allentown/Bethlehem/Easton, PA","Tampa, FL (Metropolitan Area)",ABE,TPA,19,208.93,DL,970
2,2021,3,"Albuquerque, NM","Dallas/Fort Worth, TX",ABQ,DAL,204,184.56,WN,580
3,2021,3,"Albuquerque, NM","Dallas/Fort Worth, TX",ABQ,DFW,264,182.64,AA,580
4,2021,3,"Albuquerque, NM","Phoenix, AZ",ABQ,PHX,398,177.11,WN,328

### Menangani *missing values*, menghapus anomali data, dan memastikan tipe data

In [13]:
# Menghapus baris dengan nilai NaN
df_clean.dropna(inplace=True)

# Menghapus data anomali (Fare <= 0 atau Passengers <= 0)
df_clean = df_clean[(df_clean['fare'] > 0) & (df_clean['passengers'] > 0)]

# Memastikan tipe data sudah benar (Numerik)
df_clean['Year'] = df_clean['Year'].astype(int)
df_clean['quarter'] = df_clean['quarter'].astype(int)
df_clean['passengers'] = df_clean['passengers'].astype(int)
df_clean['fare'] = df_clean['fare'].astype(float)

### Menambah Kolom Baru
1. **Route**: Menggabungkan kota dan kode bandara.
2. **Era**: Mengelompokkan tahun berdasarkan peristiwa sejarah: Normal, 9/11, Krisis 2008, Pandemi COVID-19.

In [10]:
# 1. Kolom Route
df_clean['Route'] = df_clean['city1'] + ' (' + df_clean['airport_1'] + ') - ' + df_clean['city2'] + ' (' + df_clean['airport_2'] + ')'

# 2. Membuat Kolom Era
def kategori_era(year):
    if year <= 2000:
        return 'Normal Era (1993-2000)'
    elif 2001 <= year <= 2007:
        return '9/11 Impact & Recovery (2001-2007)'
    elif 2008 <= year <= 2019:
        return 'Financial Crisis & Stability (2008-2019)'
    elif year >= 2020:
        return 'Pandemic & New Normal (2020-2024)'
    return 'Unknown'

df_clean['Era'] = df_clean['Year'].apply(kategori_era)

# Cek hasil penambahan kolom
df_clean[['Year', 'Era', 'Route']].head()

,Year,Era,Route
0,2021,Pandemic & New Normal (2020-2024),"Allentown/Bethlehem/Easton, PA (ABE) - Tampa, ..."
1,2021,Pandemic & New Normal (2020-2024),"Allentown/Bethlehem/Easton, PA (ABE) - Tampa, ..."
2,2021,Pandemic & New Normal (2020-2024),"Albuquerque, NM (ABQ) - Dallas/Fort Worth, TX ..."
3,2021,Pandemic & New Normal (2020-2024),"Albuquerque, NM (ABQ) - Dallas/Fort Worth, TX ..."
4,2021,Pandemic & New Normal (2020-2024),"Albuquerque, NM (ABQ) - Phoenix, AZ (PHX)"

In [11]:
# mengecek ulang sebelum disimpan di file baru
df_clean.info()

<class 'pandas.core.frame.DataFrame'>
Index: 238057 entries, 0 to 245954
Data columns (total 12 columns):
 #   Column      Non-Null Count   Dtype
---  ------      --------------   -----
 0   Year        238057 non-null  int64
 1   quarter     238057 non-null  int64
 2   city1       238057 non-null  object
 3   city2       238057 non-null  object
 4   airport_1   238057 non-null  object
 5   airport_2   238057 non-null  object
 6   passengers  238057 non-null  int64
 7   fare        238057 non-null  float64
 8   carrier_lg  238057 non-null  object
 9   nsmiles     238057 non-null  int64
 10  Route       238057 non-null  object
 11  Era         238057 non-null  object
dtypes: float64(1), int64(4), object(7)
memory usage: 23.6+ MB

In [12]:
df_clean.to_csv('Flight_Data_Final.csv', index=False)

print("Berhasil! File 'Flight_Data_Final.csv' sudah siap dipakai untuk Tableau.")

Berhasil! File 'Flight_Data_Final.csv' sudah siap dipakai untuk Tableau.